### PR TITLE
Trigger /N on connect and nick change

### LINKED ISSUE #41: /N masks now *only* trigger on nick change
masks ending in `/N` should trigger on both connect and nick change

### PR DESCRIPTION
**Pull request by examknow**
Closes #41

### CODE REVIEW

**Comment by jesopo** [comment]
problem is this means that masks without `/N` will also trigger on nick change. the simple set logic doesn't work for this

**Comment by jesopo** [comment]
if masks worked on nick changes by default and adding `/N` meant that they didn't work on nick changes, then adding `N` to `uflags` when we're handling `Event.CONNECT` then that would work

**Comment by examknow** [comment]
I personally don't see a problem with checking nick changes by default

**Comment by jesopo** [comment]
the vast majority if the time you're only targeting things that connect with a given pattern and not triggering on nick change is an easy win for less false positives

**Comment by jesopo** [comment]
I'll have a think

**Comment by examknow** [comment]
Closing per #46

**Pull request closed without merging**
